# 開発メモ
:author: slow life pg
:icons: font

## type stub
openpyxlをインストールしただけではmypyが全てを把握しきれないらしい。

[source, shell]
....
python -m pip install types-openpyxl
....

## pytestでデバッグ
コマンドパレットで``python config tests``を叩いて、``pytest``を選ぶ。

成功すればサイドバーにフラスコアイコンが表示されるので、そこから個別に実行もデバッグもできる。

## テストモジュールの分離
ツールは``src``、テストは``test``に書きたい。
テスト実行時は親階層をまたぐため``import``できない。

様々な方法があるらしいが今回は最も簡潔だった``conftest.py``で解決する。

pytest的には標準的な動きではないと注意しているブログもあったが、使えるなら問題ない。

mypyエラーは設定で回避。

[source, json]
....
"python.analysis.extraPaths": [
    "${workspaceFolder}/src"
],
....

## 不思議な挙動
### printできない
テストコードの中で``print``を書いても、成功した場合は実行結果に表示されない。
確かに邪魔と言えば邪魔だが、あって悪いことはないと思う。

### Testと名の付くクラスに警告
実行時にクラス名に"Test"が付くものがあると警告が出る。

----
PytestCollectionWarning: cannot collect test class 'TestScope' because it has a __init__ constructor
----

### テスト関数のローカル値が残る
``class``の属性はコンストラクタで代入することで作らなければならない。
なぜか、そうしないとグローバル変数扱いになる。

[source, python]
....
# NG
class A:
    member: str

# OK
class B:
    def __init__(self):
        self.member = ""
....

### ByRefはVariantでなければ「型が一致しません」エラー
[source, VB]
....
Public Sub GetCellValueRef(ByVal row As Integer, ByVal col As Integer, ByRef value As Variant)
....

## エラー警告抑制
### PyLint
PyLint:Args
|=番号=|=説明=|
|W0718|try-exceptでExceptionをキャッチすると警告|

### Ruff
|=番号=|=説明=|
|E402|import文がファイルの先頭に無い|

## VBAの許可
Excel -> ファイル -> オプション -> トラストセンター -> トラストセンターの設定 -> 信頼できる場所 -> 「サブフォルダも」
