[tool.ruff]
target-version = "py311"
src = ["src", "test"]
line-length = 150
indent-width = 4
docstring-code-format = true
docstring-code-line-length = 200
exclude = [".env", "Bridge"]
ignore = [
    # E501(line length)はコメント行で無視したいのでnoqaで対応
    "RUF100", # E501を無視してもエラーにならないだけで整形はされるのをnoqaで止めたいが無意味だと言われるので除外
]
select = ["ALL"] # すべてのルールを適用する

[tool.ruff.format]
exclude = [".env", "Bridge"]

[tool.ruff.lint]
exclude = [".env", "Bridge"]

[tool.ruff.pydocstyle]
convention = "google" # docstringの形式を指定

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
